export const PHASE_DURATIONS = {
  drawing: 90_000,
  guessing: 45_000,
  voting: 30_000,
} as const;

export const INACTIVE_AFTER_MS = 120_000;
export const MAX_ROUNDS = 3;
export const MIN_PLAYERS = 2;

export const PROMPTS = [
  "Kafa sa šlagom",
  "Planina Bjelašnica",
  "Sarajevska ruža",
  "Ćevapi u somunu",
  "Stari most Mostar",
  "Baščaršija",
  "Sebilj",
  "Bosanski lonac",
  "Tradicionalna nošnja",
  "Begova džamija",
  "Burek sa sirom",
  "Fildžan kafe",
  "Treska planina",
  "Una rijeka",
  "Bosanska kuća",
  "Sevdalinka",
  "Rakija",
  "Bosanski ćilim",
  "Avlija",
  "Zimska olimpijada",
  "Tulumbe",
  "Hurmasice",
  "Baklava",
  "Zeljanica",
  "Tufahije",
  "Šljivovica",
  "Bosanski konak",
  "Džezva",
  "Sahan",
  "Sinija",
  "Janje na ražnju",
  "Vijećnica",
  "Uštipci",
  "Kozji most",
  "Vrelo Bosne",
  "Šadrvan",
  "Sarma",
  "Punjena paprika",
  "Grah",
  "Krempita",
  "Oklagija",
  "Vrelo Bune",
  "Bobovac",
  "Vodopad",
  "Sutjeska",
];
